name: "xOpera docs workflow"

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install prerequisite Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install prerequisite Latex packages
        run: sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - name: Build HTML docs
        run: sphinx-build -M html docs build
      - name: Build Latex and PDF docs
        run: sphinx-build -M latexpdf docs build
      - name: Upload HTML documentation artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: docs-html
          path: build/html
      - name: Upload PDF documentation artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: docs-pdf
          path: build/latex/xopera-documentation.pdf

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download HTML docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-html
          path: build/html
      - name: Deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
